# 1.1 Creating Vector

In [4]:
import numpy as np

In [5]:
vector_row = np.array([1, 2, 3])
vector_row

array([1, 2, 3])

In [10]:
vector_column = np.array([[1],
                         [2],
                         [3]])

vector_column

array([[1],
       [2],
       [3]])

# 1.2 Creating Matrix

In [11]:
vector_matrix = np.array([[1, 3],
                         [2, 4],
                         [3, 2]])

vector_matrix

array([[1, 3],
       [2, 4],
       [3, 2]])

In [12]:
matrix_obj = np.matrix([
    [1, 2],
    [3, 4],
    [5, 6]
])

matrix_obj

matrix([[1, 2],
        [3, 4],
        [5, 6]])

# Creating a Sparse Matrix

In [ ]:
from scipy import sparse

In [25]:
mtx = np.array([
    [0, 2],
    [3, 0],
    [0, 567]
])

mtx

array([[  0,   2],
       [  3,   0],
       [  0, 567]])

In [26]:
mtx_sparse = sparse.csr_matrix(mtx)

In [27]:
mtx_sparse

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3 stored elements and shape (3, 2)>

In [28]:
print(mtx_sparse)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3 stored elements and shape (3, 2)>
  Coords	Values
  (0, 1)	2
  (1, 0)	3
  (2, 1)	567


- Non zeros values only we can found

In [29]:
# Create larger matrix
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [30]:
mtx_large_sparse = sparse.csr_matrix(matrix_large)

In [31]:
mtx_large_sparse

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 10)>

In [32]:
print(mtx_large_sparse)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 10)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3


# 1.4 Selecting Elements

In [33]:
v = np.array([1, 2, 3, 4, 5, 6, 7])

In [34]:
v

array([1, 2, 3, 4, 5, 6, 7])

In [35]:
# Create matrix
matrix = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])

In [36]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
v[2]

np.int64(3)

In [ ]:
matrix[0, 2] # row, col

np.int64(3)

In [41]:
v[:]

array([1, 2, 3, 4, 5, 6, 7])

In [43]:
v[:-1]

array([1, 2, 3, 4, 5, 6])

In [44]:
matrix[:2,:]


array([[1, 2, 3],
       [4, 5, 6]])

# 1.5 Describing Matrix

In [45]:
ix = np.array([[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12]])

In [46]:
ix.shape

(3, 4)

In [47]:
ix.size

12

In [48]:
ix.ndim

2

# 1.6 Applying Operations to Elements

In [49]:
ix = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])

In [55]:
add_100 = lambda i: i+100

In [56]:
add_100

<function __main__.<lambda>(i)>

In [57]:
vectorized_add_100 = np.vectorize(add_100)

In [58]:
vectorized_add_100

In [59]:
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [ ]:
# simple version
# This is called broadcasting
ix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

# 1.7 Finding the Maximum and Minimum Values

In [61]:
np.max(ix)

np.int64(9)

In [63]:
np.min(ix)

np.int64(1)

In [67]:
ix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
# each column max
np.max(ix, axis=1)

array([3, 6, 9])

In [65]:
# each row max
np.max(ix, axis=1)

array([3, 6, 9])

# 1.8 Calculating the Average, Variance, and Standard Deviation

In [68]:
np.mean(ix)

np.float64(5.0)

In [69]:
np.var(ix)

np.float64(6.666666666666667)

In [70]:
np.std(ix)

np.float64(2.581988897471611)

In [72]:
ix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
np.mean(ix, axis=0)

array([4., 5., 6.])

# 1.9 Reshaping Arrays

In [ ]:
matrix = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12]])

In [ ]:
matrix

In [74]:
matrix.reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [75]:
matrix.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [76]:
matrix.size

12

In [77]:
matrix.reshape(12) # flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [78]:
matrix.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

# 1.10 Transposing a Vector or Matrix

In [79]:
matrix.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [80]:
np.array([1, 2, 3, 4, 5, 6]).T

array([1, 2, 3, 4, 5, 6])

In [81]:
np.array([[1, 2, 3, 4, 5, 6]]).T


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

# 1.11 Flattening a Matrix

In [83]:
matrix.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# 1.12 Finding the Rank of a Matrix

In [85]:
np.linalg.matrix_rank(matrix)

np.int64(2)

# 1.13 Calculating the Determinant

In [ ]:
# np.linalg.det(matrix)

LinAlgError: Last 2 dimensions of the array must be square

In [87]:
# Create matrix
matrix = np.array([[1, 2, 3],
                [2, 4, 6],
                [3, 8, 9]])



In [88]:
# Return determinant of matrix
np.linalg.det(matrix)

np.float64(0.0)

- https://mathworld.wolfram.com/topics/Algebra.html

# 1.14 Getting the Diagonal of a Matrix

In [90]:
matrix

array([[1, 2, 3],
       [2, 4, 6],
       [3, 8, 9]])

In [89]:
matrix.diagonal()

array([1, 4, 9])

In [91]:
# above
matrix.diagonal(offset=1)

array([2, 6])

In [92]:
# below
matrix.diagonal(offset=-1)

array([2, 8])

# 1.15 Calculating the Trace of a Matrix

In [95]:
# diagonal sum
matrix.trace()

np.int64(14)

In [94]:
sum(matrix.diagonal())

np.int64(14)

# 1.16 Finding Eigenvalues and Eigenvectors

http://mathonline.wikidot.com/

In [96]:
np.linalg.eig(matrix)

EigResult(eigenvalues=array([ 1.48102497e+01, -3.89956396e-16, -8.10249676e-01]), eigenvectors=array([[-2.52429940e-01, -9.48683298e-01, -3.38042383e-01],
       [-5.04859881e-01, -4.68266473e-17, -6.76084766e-01],
       [-8.25466914e-01,  3.16227766e-01,  6.54703549e-01]]))

In [97]:
eig_values, eig_vectors = np.linalg.eig(matrix)

In [98]:
eig_values

array([ 1.48102497e+01, -3.89956396e-16, -8.10249676e-01])

In [99]:
eig_vectors

array([[-2.52429940e-01, -9.48683298e-01, -3.38042383e-01],
       [-5.04859881e-01, -4.68266473e-17, -6.76084766e-01],
       [-8.25466914e-01,  3.16227766e-01,  6.54703549e-01]])

https://setosa.io/ev/eigenvectors-and-eigenvalues/

# 1.17 Calculating Dot Products

In [100]:
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

In [101]:
np.dot(vector_a, vector_b)

np.int64(32)

In [ ]:
vector_a @ vector_b # python 3.5+ version

np.int64(32)

# 1.18 Adding and Subtracting Matrices

In [103]:
# Create matrix
matrix_a = np.array([[1, 1, 1],
 [1, 1, 1],
 [1, 1, 2]])

# Create matrix
matrix_b = np.array([[1, 3, 1],
 [1, 3, 1],
 [1, 3, 8]])

In [104]:
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [105]:
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [106]:
matrix_a + matrix_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [107]:
matrix_a - matrix_b

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

# 1.19 Multiplying Matrices

In [108]:
np.dot(matrix_a, matrix_b)

array([[ 3,  9, 10],
       [ 3,  9, 10],
       [ 4, 12, 18]])

In [109]:
matrix_a @ matrix_b

array([[ 3,  9, 10],
       [ 3,  9, 10],
       [ 4, 12, 18]])

In [110]:
matrix_a * matrix_b

array([[ 1,  3,  1],
       [ 1,  3,  1],
       [ 1,  3, 16]])

# 1.20 Inverting a Matrix

In [114]:
mtx120 = np.array([[1, 2], [3, 4]])

In [115]:
np.linalg.inv(mtx120)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [116]:
# multiple with its inverse

mtx120 @ np.linalg.inv(mtx120)

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

# 1.21 Generating Random Values

In [117]:
np.random.seed(0)

In [ ]:
np.random.random(3) # (0, 1)

array([0.5488135 , 0.71518937, 0.60276338])

In [122]:
np.random.randint(0, 12, 3)

array([7, 6, 8], dtype=int32)

In [123]:
# Draw three numbers from a normal distribution with mean 0.0
# and standard deviation of 1.0
np.random.normal(0.0, 1.0, 3)

array([-0.10321885,  0.4105985 ,  0.14404357])

In [ ]:
np.random.normal(1., 2., 3)

array([3.90854701, 1.88772647, 1.66734865])

In [124]:
# Draw three numbers from a logistic distribution with mean 0.0 and scale of 1.0
np.random.logistic(0.0, 1.0, 3)

array([ 0.27387744,  2.52093742, -2.57088231])

In [125]:
# Draw three numbers greater than or equal to 1.0 and less than 2.0
np.random.uniform(1.0, 2.0, 3)

array([1.0871293 , 1.0202184 , 1.83261985])